spring:
  application:
    name: blps
  
  # Профиль по умолчанию для локальной разработки
  profiles:
    active: dev
  
  # Общие настройки JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

# Настройки сервера
server:
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

# JWT настройки (общие)
jwt:
  expiration: 86400000  # 24 часа

# OpenAPI настройки (общие)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  writer-with-default-pretty-printer: true
  paths-to-match: /api/v1/**

# Настройки логирования (общие)
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
